import Navbar from "@/components/Layout/Navbar";
import "./globals.css";

import { Outfit, Lora } from 'next/font/google'
import Footer from "@/components/Layout/Footer";

const outfit = Outfit({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en " >
      <body className={`${outfit.className} md:px-12 p-2 `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
