import Navbar from "@/components/Layout/Navbar";
import "./globals.css";

import { Outfit, Lora } from 'next/font/google'
import Footer from "@/components/Layout/Footer";
import { Toaster } from "react-hot-toast";
import ContextProvider from "@/components/ContexProvider";

const outfit = Outfit({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en " >

      <body className={`${outfit.className} px-2 lg:px-24 `}>
      <ContextProvider>
      <Navbar />

      <Toaster
  position="bottom-center"
  reverseOrder={false}
/>
        {children}
        <Footer />
      </ContextProvider>
      
      </body>
    </html>
  );
}
